### ISSUE TITLE
Official download page

### ISSUE THREAD

**Issue by Nosirus** [sjtug/caddy2-filter#5]
Is it possible that it is on the official page?

**Comment by htfy96** [comment]
Hi
Thanks for your report.

I've claimed this package on caddy2's website but it seems that there might be some incompatibility making this package displayed as `not adding any new plugins`. Will investigate it later.

**Comment by htfy96** [comment]
Checked again just now and it's appearing on https://caddyserver.com/download. I'm closing this now. Feel free to let me know any further issue.
